apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
   # path: "/tmp/kube"
  nfs:
    server: "10.95.65.213"
    path: "srv/nfs/kube"
